language: rust
sudo: false
cache: cargo
stages:
  - test
  - deploy
addons:
  firefox: latest
  chrome: stable
before_script:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
script:
  - wasm-pack build
  - cargo test
  - wasm-pack test --chrome --firefox --headless
  - rimraf dist pkg && webpack
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
  target_branch: gh-pages
  local_dir: dist


